#!/usr/bin/env bash
# A script that prints a string iteratively and
# a special string when recieving a kill signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am Invincible!!!"'
done
