#!/usr/bin/env bash
# Display a string if multiple of 5 and/or 3

for n in {1..100}
do
	if ((n % 3 == 0 && n % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((n % 3 == 0))
	then
		echo "Fizz"
	elif ((n % 5 == 0))
	then
		echo "Buzz"
	else 
		echo "$n"
	fi
done
