#!/usr/bin/env bash
# A script that prints a string with exception 
# at 8th and 4th position

index=1
while [ $index -le 10 ]
do
	if [ $index -eq 4 ]
	then
		echo "bad lack"
	elif [ $index -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((index++))
done
